#include "mandlebrot_drawer.hpp"
#include "bandt_drawer.hpp"
#include "N_drawer.hpp"
#include "zoom_in_tool.hpp"
#include "N_attractor_plotting.hpp"
#include "thicken_image.hpp"
#include "utils.hpp"
using namespace frc;
int main()
{
    //auto [q_res, q_dom, q_pic_name] = generate_domain_and_resolution(std::complex(0.0, 0.0), 2);
    //draw_mandlebrot(std::format("pics/mandlebrot_{}_depth_{}.bmp", q_pic_name, 100),
    //    {q_res, q_dom}, 100);

    //auto [m_res, m_dom, m_pic_name] = 
    //    generate_domain_and_resolution(std::complex(1/std::sqrt(8), 1 / std::sqrt(8)), 1 / std::sqrt(8));
    //draw_M(std::format("pics/bandt_{}_depth_{}.bmp", m_pic_name, 20),
    //    {m_res, m_dom}, 20);

    //draw_mandlebrot("pics/mandlebrot_debug.bmp",
    //    {resolution_t{ 600, 600 },
    //    picture_domain_t{ .x{-1, 1}, .y{-1, 1 } }},
    //    100);

    /*draw_M("pics/M_debug.bmp",
        {resolution_t{ 600, 600 },
        picture_domain_t{ .x{0, 1.0}, .y{0, 1.0} }}, 50);*/
     
    ////This point was generated by a different program
    //std::complex potential_pt = { 0.602771333745229, 0.7501489829916319 };
    //auto [res, dom, pic_name] = 
    //    generate_domain_and_resolution(potential_pt, 0.01);
    //draw_N("pics/candidate_pt.bmp", { res, dom }, 40);
    //draw_N("pics/N_debug.bmp",
    //    {resolution_t{ 600, 600 },
    //    picture_domain_t{ .x{0.5,1}, .y{0.5,1} }}, 20);

    // this parameter was calculated numerically so it has a trap with words of length 10
    frc::r2vec_t param = { 0.6007429091455938, 0.7685732096627909 };
    std::string image_path = "pics/new_attr_zoom_trap_23.bmp";
    plot_partial_N_attractor(param,
        image_path,
    frc::resolution_t{ 40, 800 },
    23);
    bitmap_image img(image_path);
    plot_4_trap_points(param, img);
    bitmap_image thickened = thicken(img, 3);
    thickened.save_image("pics/new_attr_thickened.bmp");

    return 0;
}
